#!/usr/bin/env bash
#
clear
echo -e "\nEXPANSÃO DE STRINGS\n"

echo -e "# CREI UMA VARIAVEL COM O CONTEUDO: LUCAS NOBRE FERREIRA MARTINS\n"
VARIAVEL="LUCAS NOBRE FERREIRA MARTINS"

echo "PARA RETORNAR A QUANTIDADE DE CARACTERES USE #"
echo "${#VARIAVEL}"

echo -e "\n#CORTAR STRINGS COMEÇANDO DO INICIO DA STRING"
echo "${VARIAVEL#LUCAS }"

echo -e "\n#CORTAR CARACTERES PELO PARAMETRO DETERMINADO NA STRING STRING"
echo "${VARIAVEL:3}"

echo -e "\n#CORTAR CARACTERES PELOS PARAMETRO DETERMINADO NA STRING STRING"
echo "${VARIAVEL:6:5}"

echo -e "\n#SUBSTITUIR A PRIMEIRA OCORRENCIA PELOS PARAMETRO DETERMINADO NA STRING STRING"
echo "${VARIAVEL/LUCAS/DANIEL}"

echo -e "\n#SUBSTITUIR TODAS AS OCORRENCIA PELOS PARAMETRO DETERMINADO NA STRING STRING"
echo "${VARIAVEL//R/L}"

echo -e "\n#ALTERANDO A PRIMEIRA OCORRENCIA ENCONTRADA NUMA STRING"
echo "${VARIAVEL/#LUCAS/MATHEUS}"

echo -e "\n#ALTERANDO A ULTIMA OCORRENCIA ENCONTRADA NUMA STRING."
echo "${VARIAVEL/%MARTINS/LIMA}"



